// userConstants.js

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPLOAD_USER_PROFILE_IMAGE = 'UPLOAD_USER_PROFILE_IMAGE';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const UPDATE_USER_CONTACT = 'UPDATE_USER_CONTACT';
export const UPDATE_USER_QUALIFICATION = 'UPDATE_USER_QUALIFICATION';
export const UPDATE_USER_OTHER_QUALIFICATION = 'UPDATE_USER_OTHER_QUALIFICATION';
export const UPDATE_USER_JOB_ROLE = 'UPDATE_USER_JOB_ROLE';
export const UPDATE_USER_SKILLS = 'UPDATE_USER_SKILLS';
export const UPDATE_USER_EXPERIENCE = 'UPDATE_USER_EXPERIENCE';
export const UPDATE_USER_PREFERRED_JOB_LOCATION = 'UPDATE_USER_PREFERRED_JOB_LOCATION';
export const UPLOAD_RESUME = 'UPLOAD_RESUME';
